# Generated by Django 3.1.12 on 2025-04-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
